package com.bsfdv.backend.infrastructure.persistence

const val EVENTS_TABLE = "EVENTS"
const val INSERT_EVENT_QUERY =
    "INSERT INTO $EVENTS_TABLE (AGGREGATE_ID, VERSION, PAYLOAD, EVENT_TYPE, AGGREGATE_TYPE, SEQ) VALUES(?,?,? FORMAT JSON,?,?,NEXT VALUE FOR EVENTS_SEQ)"
const val SELECT_EVENTS_BY_ID_QUERY = "SELECT * FROM $EVENTS_TABLE WHERE AGGREGATE_ID=?"
const val SELECT_EVENTS_BY_TYPE_QUERY = "SELECT * FROM $EVENTS_TABLE WHERE AGGREGATE_TYPE=?"