CREATE SEQUENCE EVENTS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE EVENTS (
    AGGREGATE_ID UUID NOT NULL,
    VERSION BIGINT NOT NULL,
    PAYLOAD JSON NOT NULL,
    EVENT_TYPE VARCHAR(500) NOT NULL,
    AGGREGATE_TYPE VARCHAR(500) NOT NULL,
    SEQ INT NOT NULL,
    PRIMARY KEY (AGGREGATE_ID, VERSION)
);